services:
  postgres:
    image: postgres:16
    container_name: userservice-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-userdb}
      POSTGRES_USER: ${POSTGRES_USER:-userservice}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - userservice-pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: userservice-redis
    ports:
      - "6379:6379"

  openbao:
    image: openbao/openbao:2.6
    container_name: novabank-secret-store
    ports:
      - "8210:8200"
    environment:
      BAO_DEV_ROOT_TOKEN_ID: dev-root-token
    command: server -dev

volumes:
  userservice-pg-data: